### ISSUE TITLE
Scarpet design

### ISSUE THREAD

**Issue by somebody1234** [gnembon/carpetmod#109]
Well, it's a good idea, but... looks like its design is not the greatest to say the least - mainly the lack of comments and comparing materials using strings, plus the fact that IMO it should be easier for people less good at programming to use, considering the playerbase of Minecraft and the goal of Scarpet. Would it be okay to do a major redesign of Scarpet?

**Comment by somebody1234** [comment]
Not to mention the current API is 1. pretty inconsistent and 2. feels hacky :/ (e.g. query and modify)

**Comment by gnembon** [comment]
strings are comments. otherwise it would not be easy to handle them with commandblocks squishing whitespaces. Also what do you mean by 'comparing materials using strings'.
And the language is as easy as it need to be to do things is meant to. What would be the other option then?
Also what do you mean that API feels hacky? It may not be complete, but what's so hacky about it.

**Comment by somebody1234** [comment]
Multiline comments (`/**/` or similar) would work equally well, and be more obviously comments. re: `query`... it seems just like a hack to work around the lack of property access syntax, same with the array access function and the lack of list and map literals. materials being strings is when you do `_ == 'grass'`, IMO it'd be better (+ faster, although that's not very important) to just make them variables

**Comment by gnembon** [comment]
language is very simple, functions and operators - positives are that they are very easy and fast to parse and compile ast from them. query is expllicitly done this way not to make a false impression that querrying for something is free like with arrays, but costs something per operation. I am not worried about that - java lists don't use [] notation although they definitely could if they wanted. You get .get and .put instead. Regarding constants - adding  a slew of constant literals would take away from the the variable space to be used for programmers, plus it would likely be slower due to spamming of the local context (or needed to be implemented differently). You can always use == block('grass') instead if that makes things clearer. It will be performing at the same speed.
